# permissions for end users to view lbregistrars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: lbregistrar-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oci-lb-controller
    app.kubernetes.io/part-of: oci-lb-controller
    app.kubernetes.io/managed-by: kustomize
  name: lbregistrar-viewer-role
rules:
- apiGroups:
  - nodes.peppy-ratio.dev
  resources:
  - lbregistrars
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodes.peppy-ratio.dev
  resources:
  - lbregistrars/status
  verbs:
  - get
