---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodes.peppy-ratio.dev
  resources:
  - lbregistrars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodes.peppy-ratio.dev
  resources:
  - lbregistrars/finalizers
  verbs:
  - update
- apiGroups:
  - nodes.peppy-ratio.dev
  resources:
  - lbregistrars/status
  verbs:
  - get
  - patch
  - update
